<a href="https://colab.research.google.com/github/pp1e/omnissiah/blob/main/media_campaign_cost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [15]:
train_df = pd.read_csv('content/train.csv')

## 1. Описание признаков

In [16]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250078 entries, 0 to 250077
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          250078 non-null  int64
 1   store_sales(in millions)    250078 non-null  float64
 2   unit_sales(in millions)     250078 non-null  float64
 3   total_children              250078 non-null  float64
 4   num_children_at_home        250078 non-null  float64
 5   avg_cars_at home(approx).1  250078 non-null  float64
 6   gross_weight                250077 non-null  float64
 7   recyclable_package          250077 non-null  float64
 8   low_fat                     250077 non-null  float64
 9   units_per_case              250077 non-null  float64
 10  store_sqft                  250077 non-null  float64
 11  coffee_bar                  250077 non-null  float64
 12  video_store                 250077 non-null  float64
 13  salad_bar                   250077 non-null  float64
 14  prepared_food               250077 non-null  float64
 15  florist                     250077 non-null  float64
 16  cost                        250077 non-null  float64
dtypes: float64(16), int64(1)
memory usage: 32.4 MB

*Таблица 1 - Описание признаков исходного датасета*

|Признак|Описание|Тип данных|Категориальный|
|-------|--------|----------|--------------|
|`id`|Уникальный идентификатор для каждой записи|int64|Нет|
|`store_sales(in millions)`|Продажи в магазине в миллионах долларов| float64|Нет|
|`unit_sales(in millions)`|Объем продаж в миллионах единиц в магазине| float64|Нет|
|`total_children`|Общее количество детей|float64| Нет|
|`num_children_at_home`|Количество детей, проживающих дома, по данным, предоставленным клиентами|float64|Нет|
|`avg_cars_at home(approx)`|Среднее количество автомобилей|float64|Нет|
|`gross_weight`|Общий вес товара|float64|Нет|
|`recyclable_package`|Указывает, является ли упаковка товара перерабатываемой (0 или 1)|float64|Да|
|`low_fat`|Указывает, является ли продукт низкокалорийным (0 или 1)| float64|Да|
|`units_per_case`|Количество единиц в упаковке, доступных на полках магазина|float64|Нет|
|`store_sqft`|Площадь магазина в квадратных футах|float64|Нет|
|`coffee_bar`|Указывает, есть ли в магазине кофейня (0 или 1)|float64|Да|
|`video_store`|Указывает, есть ли в магазине видеомагазин или игровая зона (0 или 1)|float64|Да|
|`salad_bar`|Указывает, есть ли в магазине салат-бар (0 или 1)| float64| Да|
|`prepared_food`|Указывает, доступна ли в магазине готовая еда (0 или 1)| float64|Да|
|`florist`|Указывает, есть ли в магазине цветочный отдел (0 или 1)| float64|Да|
|`cost`|Стоимость привлечения клиента в долларах|float64|Нет|

**cost - целевая переменная (target)**

In [ ]:
train_df.head(10)

,id,store_sales(in millions),unit_sales(in millions),total_children,num_children_at_home,avg_cars_at home(approx).1,gross_weight,recyclable_package,low_fat,units_per_case,store_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,cost
0,0,8.61,3.0,2.0,2.0,2.0,10.30,1.0,0.0,32.0,36509.0,0.0,0.0,0.0,0.0,0.0,62.09
1,1,5.00,2.0,4.0,0.0,3.0,6.66,1.0,0.0,1.0,28206.0,1.0,0.0,0.0,0.0,0.0,121.80
2,2,14.08,4.0,0.0,0.0,3.0,21.30,1.0,0.0,26.0,21215.0,1.0,0.0,0.0,0.0,0.0,83.51
3,3,4.02,3.0,5.0,0.0,0.0,14.80,0.0,1.0,36.0,21215.0,1.0,0.0,0.0,0.0,0.0,66.78
4,4,2.13,3.0,5.0,0.0,3.0,17.00,1.0,1.0,20.0,27694.0,1.0,1.0,1.0,1.0,1.0,111.51
5,5,9.08,4.0,5.0,5.0,3.0,7.26,0.0,1.0,5.0,33858.0,1.0,0.0,1.0,1.0,1.0,142.58
6,6,4.80,2.0,1.0,0.0,2.0,9.58,0.0,0.0,6.0,27694.0,1.0,1.0,1.0,1.0,1.0,69.47
7,7,4.29,3.0,2.0,0.0,2.0,16.90,1.0,0.0,2.0,23688.0,1.0,1.0,1.0,1.0,1.0,68.84
8,8,8.55,3.0,5.0,0.0,2.0,13.80,1.0,0.0,6.0,38382.0,0.0,0.0,0.0,0.0,0.0,87.07
9,9,3.08,4.0,1.0,0.0,3.0,15.70,1.0,1.0,9.0,27694.0,1.0,1.0,1.0,1.0,1.0,80.29

In [7]:
train_df.describe()

,id,store_sales(in millions),unit_sales(in millions),total_children,num_children_at_home,avg_cars_at home(approx).1,gross_weight,recyclable_package,low_fat,units_per_case,store_sqft,coffee_bar,video_store,salad_bar,prepared_food,florist,cost
count,250078.000000,250078.000000,250078.000000,250078.000000,250078.000000,250078.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000,250077.000000
mean,125038.500000,6.334813,3.044054,2.455894,0.687877,2.202657,13.816485,0.568129,0.327747,18.972528,28185.707550,0.564906,0.277487,0.504944,0.504964,0.503469,99.620050
std,72191.444647,3.305808,0.785092,1.490106,1.213486,1.084927,4.614722,0.495338,0.469393,10.213983,5965.521126,0.495770,0.447759,0.499977,0.499976,0.499989,29.941742
min,0.000000,0.510000,1.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,1.000000,20319.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.790000
25%,62519.250000,3.720000,3.000000,1.000000,0.000000,1.000000,9.710000,0.000000,0.000000,10.000000,23593.000000,0.000000,0.000000,0.000000,0.000000,0.000000,70.320000
50%,125038.500000,5.760000,3.000000,2.000000,0.000000,2.000000,13.600000,1.000000,0.000000,20.000000,27694.000000,1.000000,0.000000,1.000000,1.000000,1.000000,98.810000
75%,187557.750000,8.400000,4.000000,4.000000,1.000000,3.000000,17.700000,1.000000,1.000000,28.000000,33858.000000,1.000000,1.000000,1.000000,1.000000,1.000000,126.620000
max,250077.000000,22.920000,6.000000,5.000000,5.000000,4.000000,21.900000,1.000000,1.000000,36.000000,39696.000000,1.000000,1.000000,1.000000,1.000000,1.000000,149.750000

In [9]:
train_df.shape

(250078, 17)